### PR TITLE
found a source for MFSimpleEncode, but without .cvproj and .sln

### PR DESCRIPTION
**Pull request by crackwitz**
http://en.pudn.com/Download/item/id/1962680.html

### CODE REVIEW

**Comment by roman380** [comment]
I am aware of this resource and I tried to download from three a few times in past but I could not pass registration form. Anyway, I see now that indeed it's possible to pull individual files so maybe it's good enough to restore the original project. Thanks!

**Comment by crackwitz** [comment]
MFCopy.vcproj contains the string `RootNamespace="MFSimpleEncode"` so it might itself have been an offshoot of MFSimpleEncode... i.e. the vcproj and sln might be easy to fix up

**Comment by roman380** [comment]
Oh I missed your pushing those files available, and re-added them myself...

**Comment by roman380** [comment]
I will close the PR and you can pull from my branch once again - I re-created .sln and .vcproj files there as well.

**Pull request closed without merging**
